import { ColorRecipe, HSLChannel, ToneCurvePoint } from '../types';

/**
 * Lightroom XMP Develop Preset Generator & Validator
 * Converts structured ColorRecipe into valid Adobe Lightroom Camera Raw .xmp presets.
 */

export interface RecipeValidationResult {
  valid: boolean;
  recipe?: ColorRecipe;
  errors: string[];
}

export interface XmpValidationResult {
  valid: boolean;
  errors: string[];
  developSettingsCount: number;
}

function clamp(val: number | undefined | null, min: number, max: number, fallback = 0): number {
  if (val === undefined || val === null || isNaN(val) || !isFinite(val)) {
    return fallback;
  }
  return Math.min(Math.max(val, min), max);
}

function sanitizeNumber(val: any, min: number, max: number, fallback = 0): number {
  if (typeof val === 'string') {
    const parsed = parseFloat(val);
    return isNaN(parsed) ? fallback : clamp(parsed, min, max, fallback);
  }
  if (typeof val === 'number') {
    return clamp(val, min, max, fallback);
  }
  return fallback;
}

function sanitizeHSL(channel: any, isSkinChannel = false): HSLChannel {
  const minHue = isSkinChannel ? -30 : -100;
  const maxHue = isSkinChannel ? 30 : 100;
  const minSat = isSkinChannel ? -35 : -100;
  const maxSat = isSkinChannel ? 35 : 100;
  const minLum = isSkinChannel ? -30 : -100;
  const maxLum = isSkinChannel ? 30 : 100;

  return {
    hue: Math.round(sanitizeNumber(channel?.hue, minHue, maxHue, 0)),
    saturation: Math.round(sanitizeNumber(channel?.saturation, minSat, maxSat, 0)),
    luminance: Math.round(sanitizeNumber(channel?.luminance, minLum, maxLum, 0)),
  };
}

function sanitizeToneCurve(points: any[] | undefined): ToneCurvePoint[] {
  if (!points || !Array.isArray(points) || points.length === 0) {
    return [
      { x: 0, y: 0 },
      { x: 255, y: 255 },
    ];
  }

  const sanitized: ToneCurvePoint[] = points
    .map((pt) => {
      let x = sanitizeNumber(pt?.x, 0, 255, 0);
      let y = sanitizeNumber(pt?.y, 0, 255, 0);
      // If values were given in 0-100 scale, normalize to 0-255
      if (pt?.x <= 100 && pt?.y <= 100 && points.every((p) => p.x <= 100 && p.y <= 100)) {
        x = Math.round((x / 100) * 255);
        y = Math.round((y / 100) * 255);
      }
      return { x: Math.round(x), y: Math.round(y) };
    })
    .sort((a, b) => a.x - b.x);

  // Ensure start and end points exist
  if (sanitized.length === 0 || sanitized[0].x > 0) {
    sanitized.unshift({ x: 0, y: 0 });
  }
  if (sanitized[sanitized.length - 1].x < 255) {
    sanitized.push({ x: 255, y: 255 });
  }

  return sanitized;
}

/**
 * Validates and cleanses a raw color recipe against Lightroom safe bounds.
 */
export function validateColorRecipe(raw: any): RecipeValidationResult {
  const errors: string[] = [];

  if (!raw || typeof raw !== 'object') {
    return { valid: false, errors: ['Color recipe must be a valid JSON object.'] };
  }

  const presetName = (raw.presetName || 'ZAP Color Preset').trim();
  const description = (raw.description || 'Lightroom Develop Preset generated by ZAP Visual Guide').trim();

  // White Balance
  const wb = raw.whiteBalance || {};
  let tempKelvin = 5600;
  if (wb.temperature !== undefined && wb.temperature !== null && !isNaN(Number(wb.temperature))) {
    const rawVal = Number(wb.temperature);
    if (rawVal >= 2000 && rawVal <= 12000) {
      tempKelvin = Math.round(rawVal);
    } else if (rawVal >= -100 && rawVal <= 100) {
      // Relative offset normalized to daylight 5600K
      tempKelvin = Math.round(5600 + rawVal * 20);
    } else if (rawVal > 12000) {
      tempKelvin = 12000;
      errors.push(`Temperature ${rawVal}K exceeded maximum allowable range, clamped to 12000K.`);
    } else if (rawVal < 2000) {
      tempKelvin = 2000;
      errors.push(`Temperature ${rawVal}K below minimum allowable range, clamped to 2000K.`);
    }
  }

  const safeMode: 'Custom' | 'As Shot' = wb.mode === 'As Shot' ? 'As Shot' : 'Custom';
  const safeTint = Math.round(sanitizeNumber(wb.tint, -150, 150, 0));

  const whiteBalance = {
    mode: safeMode,
    temperature: clamp(tempKelvin, 2000, 12000, 5600),
    tint: safeTint,
  };

  // Safe client debug logging ONLY for white balance parameters
  console.log(
    `[ColorRecipe Debug] Validated White Balance -> temperature: ${whiteBalance.temperature}K, tint: ${
      whiteBalance.tint > 0 ? `+${whiteBalance.tint}` : whiteBalance.tint
    }, mode: ${whiteBalance.mode}`
  );

  // Basic Tonal Settings
  const b = raw.basic || {};
  const exposureRaw = sanitizeNumber(b.exposure, -5.0, 5.0, 0.0);
  const exposure = Math.round(exposureRaw * 100) / 100;

  const basic = {
    exposure,
    contrast: Math.round(sanitizeNumber(b.contrast, -100, 100, 0)),
    highlights: Math.round(sanitizeNumber(b.highlights, -100, 100, 0)),
    shadows: Math.round(sanitizeNumber(b.shadows, -100, 100, 0)),
    whites: Math.round(sanitizeNumber(b.whites, -100, 100, 0)),
    blacks: Math.round(sanitizeNumber(b.blacks, -100, 100, 0)),
    texture: Math.round(sanitizeNumber(b.texture, -100, 100, 0)),
    clarity: Math.round(sanitizeNumber(b.clarity, -100, 100, 0)),
    dehaze: Math.round(sanitizeNumber(b.dehaze, -100, 100, 0)),
    vibrance: Math.round(sanitizeNumber(b.vibrance, -100, 100, 0)),
    saturation: Math.round(sanitizeNumber(b.saturation, -100, 100, 0)),
  };

  // Color Mixer (HSL) - Red, Orange (protected skin), Yellow, Green, Aqua, Blue, Purple, Magenta
  const cm = raw.colorMixer || {};
  const colorMixer = {
    red: sanitizeHSL(cm.red),
    orange: sanitizeHSL(cm.orange, true), // Skin tone protection
    yellow: sanitizeHSL(cm.yellow),
    green: sanitizeHSL(cm.green),
    aqua: sanitizeHSL(cm.aqua),
    blue: sanitizeHSL(cm.blue),
    purple: sanitizeHSL(cm.purple),
    magenta: sanitizeHSL(cm.magenta),
  };

  // Color Grading (3-Way Split Toning)
  const cg = raw.colorGrading || {};
  const colorGrading = {
    shadows: {
      hue: Math.round(sanitizeNumber(cg.shadows?.hue, 0, 360, 0)),
      saturation: Math.round(sanitizeNumber(cg.shadows?.saturation, 0, 100, 0)),
      luminance: Math.round(sanitizeNumber(cg.shadows?.luminance, -100, 100, 0)),
    },
    midtones: {
      hue: Math.round(sanitizeNumber(cg.midtones?.hue, 0, 360, 0)),
      saturation: Math.round(sanitizeNumber(cg.midtones?.saturation, 0, 100, 0)),
      luminance: Math.round(sanitizeNumber(cg.midtones?.luminance, -100, 100, 0)),
    },
    highlights: {
      hue: Math.round(sanitizeNumber(cg.highlights?.hue, 0, 360, 0)),
      saturation: Math.round(sanitizeNumber(cg.highlights?.saturation, 0, 100, 0)),
      luminance: Math.round(sanitizeNumber(cg.highlights?.luminance, -100, 100, 0)),
    },
    blending: Math.round(sanitizeNumber(cg.blending, 0, 100, 50)),
    balance: Math.round(sanitizeNumber(cg.balance, -100, 100, 0)),
  };

  // Detail / Grain
  const d = raw.detail || {};
  const detail = {
    grainAmount: Math.round(sanitizeNumber(d.grainAmount, 0, 100, 0)),
    grainSize: Math.round(sanitizeNumber(d.grainSize, 0, 100, 25)),
    grainRoughness: Math.round(sanitizeNumber(d.grainRoughness, 0, 100, 50)),
  };

  // Effects / Vignette
  const eff = raw.effects || {};
  const effects = {
    vignette: Math.round(sanitizeNumber(eff.vignette, -100, 100, 0)),
  };

  // Tone Curve
  const tc = raw.toneCurve || {};
  const toneCurve = {
    rgb: sanitizeToneCurve(tc.rgb),
    red: sanitizeToneCurve(tc.red),
    green: sanitizeToneCurve(tc.green),
    blue: sanitizeToneCurve(tc.blue),
  };

  const recipe: ColorRecipe = {
    presetName,
    description,
    whiteBalance,
    basic,
    toneCurve,
    colorMixer,
    colorGrading,
    detail,
    effects,
    sourceInfo: raw.sourceInfo,
    generatedAt: raw.generatedAt || new Date().toISOString(),
  };

  return {
    valid: true,
    recipe,
    errors,
  };
}

function formatExposure(num: number): string {
  const rounded = num.toFixed(2);
  if (num > 0) return `+${rounded}`;
  if (num === 0) return `+0.00`;
  return rounded;
}

function formatSignedInt(num: number): string {
  if (num > 0) return `+${num}`;
  return `${num}`;
}

function formatCurveSeq(points: ToneCurvePoint[]): string {
  return points.map((p) => `      <rdf:li>${p.x}, ${p.y}</rdf:li>`).join('\n');
}

function escapeXml(unsafe: string): string {
  return unsafe
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;');
}

function generateUUID(): string {
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, (c) => {
    const r = (Math.random() * 16) | 0;
    const v = c === 'x' ? r : (r & 0x3) | 0x8;
    return v.toString(16).toUpperCase();
  });
}

/**
 * Generates an authentic, fully compliant Adobe Lightroom Camera Raw Develop Preset (.xmp)
 */
export function generateLightroomXmp(
  recipe: ColorRecipe,
  options?: { eventName?: string; creator?: string }
): string {
  const uuid = generateUUID();
  const safeName = escapeXml(recipe.presetName || 'ZAP Color Preset');
  const safeDesc = escapeXml(recipe.description || 'Professional Lightroom develop preset generated by ZAP Visual Guide.');

  const b = recipe.basic;
  const wb = recipe.whiteBalance;
  const cm = recipe.colorMixer;
  const cg = recipe.colorGrading;
  const d = recipe.detail;
  const eff = recipe.effects;
  const tc = recipe.toneCurve || {};

  const rgbCurve = tc.rgb && tc.rgb.length > 0 ? tc.rgb : [{ x: 0, y: 0 }, { x: 255, y: 255 }];
  const redCurve = tc.red && tc.red.length > 0 ? tc.red : [{ x: 0, y: 0 }, { x: 255, y: 255 }];
  const greenCurve = tc.green && tc.green.length > 0 ? tc.green : [{ x: 0, y: 0 }, { x: 255, y: 255 }];
  const blueCurve = tc.blue && tc.blue.length > 0 ? tc.blue : [{ x: 0, y: 0 }, { x: 255, y: 255 }];

  return `<x:xmpmeta xmlns:x="adobe:ns:meta/" x:xmptk="Adobe XMP Core 7.0-c000 1.000000, 0000/00/00-00:00:00        ">
 <rdf:RDF xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#">
  <rdf:Description rdf:about=""
   xmlns:crs="http://ns.adobe.com/camera-raw-settings/1.0/"
   crs:PresetType="Normal"
   crs:Cluster=""
   crs:UUID="${uuid}"
   crs:SupportsAmount="True"
   crs:Amount="1.000000"
   crs:ProcessVersion="15.4"
   crs:ConvertToGrayscale="False"
   crs:HasSettings="True"
   crs:HasCrop="False"
   crs:AlreadyApplied="False"
   crs:WhiteBalance="${wb.mode || 'Custom'}"
   crs:Temperature="${wb.temperature}"
   crs:Tint="${formatSignedInt(wb.tint)}"
   crs:Exposure2012="${formatExposure(b.exposure)}"
   crs:Contrast2012="${formatSignedInt(b.contrast)}"
   crs:Highlights2012="${formatSignedInt(b.highlights)}"
   crs:Shadows2012="${formatSignedInt(b.shadows)}"
   crs:Whites2012="${formatSignedInt(b.whites)}"
   crs:Blacks2012="${formatSignedInt(b.blacks)}"
   crs:Texture="${formatSignedInt(b.texture)}"
   crs:Clarity2012="${formatSignedInt(b.clarity)}"
   crs:Dehaze="${formatSignedInt(b.dehaze)}"
   crs:Vibrance="${formatSignedInt(b.vibrance)}"
   crs:Saturation="${formatSignedInt(b.saturation)}"
   crs:HueAdjustmentRed="${formatSignedInt(cm.red.hue)}"
   crs:HueAdjustmentOrange="${formatSignedInt(cm.orange.hue)}"
   crs:HueAdjustmentYellow="${formatSignedInt(cm.yellow.hue)}"
   crs:HueAdjustmentGreen="${formatSignedInt(cm.green.hue)}"
   crs:HueAdjustmentAqua="${formatSignedInt(cm.aqua.hue)}"
   crs:HueAdjustmentBlue="${formatSignedInt(cm.blue.hue)}"
   crs:HueAdjustmentPurple="${formatSignedInt(cm.purple.hue)}"
   crs:HueAdjustmentMagenta="${formatSignedInt(cm.magenta.hue)}"
   crs:SaturationAdjustmentRed="${formatSignedInt(cm.red.saturation)}"
   crs:SaturationAdjustmentOrange="${formatSignedInt(cm.orange.saturation)}"
   crs:SaturationAdjustmentYellow="${formatSignedInt(cm.yellow.saturation)}"
   crs:SaturationAdjustmentGreen="${formatSignedInt(cm.green.saturation)}"
   crs:SaturationAdjustmentAqua="${formatSignedInt(cm.aqua.saturation)}"
   crs:SaturationAdjustmentBlue="${formatSignedInt(cm.blue.saturation)}"
   crs:SaturationAdjustmentPurple="${formatSignedInt(cm.purple.saturation)}"
   crs:SaturationAdjustmentMagenta="${formatSignedInt(cm.magenta.saturation)}"
   crs:LuminanceAdjustmentRed="${formatSignedInt(cm.red.luminance)}"
   crs:LuminanceAdjustmentOrange="${formatSignedInt(cm.orange.luminance)}"
   crs:LuminanceAdjustmentYellow="${formatSignedInt(cm.yellow.luminance)}"
   crs:LuminanceAdjustmentGreen="${formatSignedInt(cm.green.luminance)}"
   crs:LuminanceAdjustmentAqua="${formatSignedInt(cm.aqua.luminance)}"
   crs:LuminanceAdjustmentBlue="${formatSignedInt(cm.blue.luminance)}"
   crs:LuminanceAdjustmentPurple="${formatSignedInt(cm.purple.luminance)}"
   crs:LuminanceAdjustmentMagenta="${formatSignedInt(cm.magenta.luminance)}"
   crs:ColorGradeMidtoneHue="${cg.midtones.hue}"
   crs:ColorGradeMidtoneSat="${cg.midtones.saturation}"
   crs:ColorGradeShadowLum="${formatSignedInt(cg.shadows.luminance || 0)}"
   crs:ColorGradeMidtoneLum="${formatSignedInt(cg.midtones.luminance || 0)}"
   crs:ColorGradeHighlightLum="${formatSignedInt(cg.highlights.luminance || 0)}"
   crs:ColorGradeBlending="${cg.blending}"
   crs:ColorGradeBalance="${formatSignedInt(cg.balance)}"
   crs:ColorGradeGlobalHue="0"
   crs:ColorGradeGlobalSat="0"
   crs:ColorGradeGlobalLum="0"
   crs:ColorGradeHighlightHue="${cg.highlights.hue}"
   crs:ColorGradeHighlightSat="${cg.highlights.saturation}"
   crs:ColorGradeShadowHue="${cg.shadows.hue}"
   crs:ColorGradeShadowSat="${cg.shadows.saturation}"
   crs:GrainAmount="${d.grainAmount}"
   crs:GrainSize="${d.grainSize}"
   crs:GrainFrequency="${d.grainRoughness}"
   crs:PostCropVignetteAmount="${formatSignedInt(eff.vignette)}"
   crs:ToneCurveName2012="Custom">
   <crs:Name>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">${safeName}</rdf:li>
    </rdf:Alt>
   </crs:Name>
   <crs:ShortDescription>
    <rdf:Alt>
     <rdf:li xml:lang="x-default">${safeDesc}</rdf:li>
    </rdf:Alt>
   </crs:ShortDescription>
   <crs:ToneCurvePV2012>
    <rdf:Seq>
${formatCurveSeq(rgbCurve)}
    </rdf:Seq>
   </crs:ToneCurvePV2012>
   <crs:ToneCurvePV2012Red>
    <rdf:Seq>
${formatCurveSeq(redCurve)}
    </rdf:Seq>
   </crs:ToneCurvePV2012Red>
   <crs:ToneCurvePV2012Green>
    <rdf:Seq>
${formatCurveSeq(greenCurve)}
    </rdf:Seq>
   </crs:ToneCurvePV2012Green>
   <crs:ToneCurvePV2012Blue>
    <rdf:Seq>
${formatCurveSeq(blueCurve)}
    </rdf:Seq>
   </crs:ToneCurvePV2012Blue>
  </rdf:Description>
 </rdf:RDF>
</x:xmpmeta>`;
}

/**
 * Validates that an XMP string is non-empty, contains valid XML,
 * declares the Camera Raw namespace, and includes actual Develop settings.
 */
export function validateXmp(xmpString: string): XmpValidationResult {
  const errors: string[] = [];
  let developSettingsCount = 0;

  if (!xmpString || typeof xmpString !== 'string' || xmpString.trim().length < 100) {
    return { valid: false, errors: ['Generated XMP file is empty or corrupted.'], developSettingsCount: 0 };
  }

  // Check XML syntax
  if (typeof window !== 'undefined' && typeof DOMParser !== 'undefined') {
    try {
      const parser = new DOMParser();
      const xmlDoc = parser.parseFromString(xmpString, 'application/xml');
      const parserError = xmlDoc.querySelector('parsererror');
      if (parserError) {
        errors.push(`XML Syntax Error: ${parserError.textContent?.slice(0, 150) || 'Malformed XML.'}`);
      }
    } catch (e: any) {
      errors.push(`XML Parser exception: ${e?.message || 'Unknown parsing failure.'}`);
    }
  }

  // Check Lightroom Camera Raw namespace
  if (!xmpString.includes('http://ns.adobe.com/camera-raw-settings/1.0/')) {
    errors.push('Missing Adobe Camera Raw settings namespace (crs).');
  }

  // Anti-corruption check: Prevent dangerous IncrementalTemperature/Tint
  if (xmpString.includes('crs:IncrementalTemperature') || xmpString.includes('crs:IncrementalTint')) {
    errors.push('Dangerous crs:IncrementalTemperature/Tint detected in develop preset (must use crs:Temperature / crs:Tint).');
  }

  // Validate White Balance properties
  const tempMatch = xmpString.match(/crs:Temperature="([^"]+)"/);
  if (tempMatch) {
    const tempVal = Number(tempMatch[1]);
    if (isNaN(tempVal) || tempVal < 2000 || tempVal > 12000) {
      errors.push(`Invalid Kelvin temperature in XMP: ${tempMatch[1]} (must be between 2000K and 12000K).`);
    }
  }

  const tintMatch = xmpString.match(/crs:Tint="([^"]+)"/);
  if (tintMatch) {
    const tintVal = Number(tintMatch[1]);
    if (isNaN(tintVal) || tintVal < -150 || tintVal > 150) {
      errors.push(`Invalid Tint in XMP: ${tintMatch[1]} (must be between -150 and +150).`);
    }
  }

  // Check for Develop settings (critical check against "no settings" bug)
  const criticalDevelopKeys = [
    'crs:Exposure2012',
    'crs:Contrast2012',
    'crs:Highlights2012',
    'crs:Shadows2012',
    'crs:Whites2012',
    'crs:Blacks2012',
    'crs:HueAdjustmentRed',
    'crs:SaturationAdjustmentRed',
    'crs:LuminanceAdjustmentRed',
    'crs:ToneCurvePV2012',
    'crs:ColorGradeHighlightHue',
  ];

  criticalDevelopKeys.forEach((key) => {
    if (xmpString.includes(key)) {
      developSettingsCount++;
    }
  });

  if (developSettingsCount < 4) {
    errors.push('XMP metadata contains insufficient or no Develop settings.');
  }

  if (!xmpString.includes('crs:HasSettings="True"')) {
    errors.push('XMP is missing crs:HasSettings="True" flag.');
  }

  if (!xmpString.includes('<crs:Name>')) {
    errors.push('XMP is missing <crs:Name> preset identifier tag.');
  }

  return {
    valid: errors.length === 0,
    errors,
    developSettingsCount,
  };
}

/**
 * Creates a controlled White Balance Test Preset to verify raw and jpeg color rendering.
 */
export function createControlledWbTestPreset(type: 'neutral' | 'warm' | 'cool'): ColorRecipe {
  const neutralHsl = { hue: 0, saturation: 0, luminance: 0 };
  const linearCurve = [
    { x: 0, y: 0 },
    { x: 255, y: 255 },
  ];

  let name = 'ZAP WB TEST (5600K)';
  let desc = 'Diagnostic preset testing 5600K daylight white balance with 0 tint and neutral develop settings.';
  let temp = 5600;
  let tint = 0;

  if (type === 'warm') {
    name = 'ZAP WB TEST WARM (6500K)';
    desc = 'Diagnostic preset testing warm 6500K golden white balance with +5 magenta tint and neutral develop settings.';
    temp = 6500;
    tint = 5;
  } else if (type === 'cool') {
    name = 'ZAP WB TEST COOL (4500K)';
    desc = 'Diagnostic preset testing cool 4500K twilight white balance with -5 green tint and neutral develop settings.';
    temp = 4500;
    tint = -5;
  }

  return {
    presetName: name,
    description: desc,
    whiteBalance: {
      mode: 'Custom',
      temperature: temp,
      tint: tint,
    },
    basic: {
      exposure: 0.0,
      contrast: 0,
      highlights: 0,
      shadows: 0,
      whites: 0,
      blacks: 0,
      texture: 0,
      clarity: 0,
      dehaze: 0,
      vibrance: 0,
      saturation: 0,
    },
    toneCurve: {
      rgb: linearCurve,
      red: linearCurve,
      green: linearCurve,
      blue: linearCurve,
    },
    colorMixer: {
      red: { ...neutralHsl },
      orange: { ...neutralHsl },
      yellow: { ...neutralHsl },
      green: { ...neutralHsl },
      aqua: { ...neutralHsl },
      blue: { ...neutralHsl },
      purple: { ...neutralHsl },
      magenta: { ...neutralHsl },
    },
    colorGrading: {
      shadows: { hue: 0, saturation: 0, luminance: 0 },
      midtones: { hue: 0, saturation: 0, luminance: 0 },
      highlights: { hue: 0, saturation: 0, luminance: 0 },
      blending: 50,
      balance: 0,
    },
    detail: {
      grainAmount: 0,
      grainSize: 25,
      grainRoughness: 50,
    },
    effects: {
      vignette: 0,
    },
    generatedAt: new Date().toISOString(),
  };
}

/**
 * Builds a clean, filesystem-safe filename for the .xmp preset.
 */
export function generatePresetFilename(presetName: string, eventName?: string): string {
  const sanitizePart = (str: string) =>
    str
      .replace(/[^a-zA-Z0-9\s_-]/g, '')
      .trim()
      .replace(/\s+/g, '_');

  const cleanPreset = sanitizePart(presetName || 'Color_Style');
  const cleanEvent = eventName ? sanitizePart(eventName) : '';

  let name = '';
  if (cleanEvent && !cleanPreset.toLowerCase().includes(cleanEvent.toLowerCase())) {
    name = `ZAP_${cleanEvent}_${cleanPreset}`;
  } else if (cleanPreset.startsWith('ZAP_')) {
    name = cleanPreset;
  } else {
    name = `ZAP_${cleanPreset}`;
  }

  // Limit filename length and add .xmp extension
  return `${name.slice(0, 64)}.xmp`;
}

/**
 * Triggers a browser download of the .xmp file
 */
export function downloadXmpPreset(xmpContent: string, filename: string): boolean {
  if (typeof window === 'undefined') return false;

  const validation = validateXmp(xmpContent);
  if (!validation.valid) {
    console.error('Download aborted: XMP validation failed:', validation.errors);
    throw new Error(`XMP validation failed: ${validation.errors.join(', ')}`);
  }

  try {
    const blob = new Blob([xmpContent], { type: 'application/x-xmp;charset=utf-8' });
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = filename.endsWith('.xmp') ? filename : `${filename}.xmp`;
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);

    // Clean up object URL after small timeout
    setTimeout(() => URL.revokeObjectURL(url), 2000);
    return true;
  } catch (err) {
    console.error('Error triggering XMP download:', err);
    throw err;
  }
}
